### ISSUE TITLE
Parameter types aren't rendered in space-separated table?

### ISSUE THREAD

**Issue by dandv** [webix-hub/docs#13]
https://github.com/webix-hub/docs/blob/master/data/api/dataloader_ondatarequest_event.md shows parameter types for `@param`, e.g. number, function, string.

But http://docs.webix.com/api__dataloader_ondatarequest_event.html displays only the parameter name and description.

**Comment by Zwillinge** [comment]
The parameter types are not reflected in the table, but they are shown in method /event description above it
~~~
void onDataRequest(number start,number count, [function callback,string url] ){ ... };
~~~
