### ISSUE TITLE
Ensure consistent tabs vs. spaces

### ISSUE THREAD

**Issue by dandv** [webix-hub/docs#20]
How can we ensure a consistent use of tabs vs. spaces throughout the documentation (and codebase)?

The majority of JS code out there uses spaces (no tabs, because they can be rendered at arbitrary widths - 2, 4, 8), [Douglas Crockford also recommends using spaces](http://javascript.crockford.com/code.html).

Regardless the choice, it would be good to be consistent about it. Webix documentation uses a mix of tabs and spaces. So far, I've converted the tabs to spaces for uniformity (see for example 1e75c6a3e2d7c89bfa13a4bec73ff12aa18bfd76).

**Comment by Zwillinge** [comment]
Actually we stick to using tabs in the code and the docs, so if any inconsistencies are found, they should be solved in favour of tabs. Thanks in advance.

**Comment by dandv** [comment]
> Actually we stick to using tabs in the code and the docs

That is a bummer.
