### ISSUE TITLE
typo for ui.uploader

### ISSUE THREAD

**Issue by rubenlagatie** [webix-hub/docs#24]
In the overview page of the ui.uploader:
http://docs.webix.com/api__refs__ui.uploader.html
The description or onFileUpload read: "fires the moment file uploading starts"

However, in the description of the event it says:
http://docs.webix.com/api__ui.uploader_onfileupload_event.html
It says: "fires the moment file uploading ends"

**Comment by Zwillinge** [comment]
The issue is fixed, thank you.
