### ISSUE TITLE
How can help?

### ISSUE THREAD

**Issue by misterx** [webix-hub/docs#28]
Some config variables newer described in documentation. I think documentation should be better. 
For example oped docs for ui.form in example used config variable "elements", but nowhere was described. I think this should be described in Values mixin. Same problem with ui.headerlayout.header, ui.view.autoheight. Would be better for each method or variable show which class is declare method or variable, if not overwritted in current class, example

## ui.form ##

* **bind** (BaseBind)
* **css** (ui.baseview)
* **container** (ui.baseview)
* **elements** (Values)
* **id** (Settings)

Where i can commit fixes for docs?

**Comment by Zwillinge** [comment]
As to UI Form API, the *elements* property is described in the "Properties" section of the article: http://docs.webix.com/api__link__ui.form_elements_config.html. The property is inherited from UI Toolbar, so it should not be described in the Values mixin.  

As to the headerlayout, the component does not feature *header* property, but each of its sub-elements, called accordionitems, does. You can check the list of its properties [here](http://docs.webix.com/api__refs__ui.accordionitem_props.html). 

Autoheight logic is not common for all the views, so the property is defined for different components (or groups of them) separately. 

As to the origin of each method/property, it does not seem to be of critical importance for the users. On the positive side, for each component we provide a list of views or mixins that are used for it. 

E.g. [Webix Accordion](http://docs.webix.com/api__refs__ui.accordion.html) - *Based on: ui.layout, ui.baselayout, EventSystem, ui.baseview, Settings, Destruction, BaseBind, UIExtension *

**Comment by misterx** [comment]
Thanks, my fail =(
