### ISSUE TITLE
What is madoka?

### ISSUE THREAD

**Issue by misterx** [webix-hub/docs#29]
I've found this
```php
require_once("../madoka/core/index.php");
```

 in docs/index.php. Where can i get this?

And codebase/core/docs_add.js , codebase/core/docs_remove.js ?

**Comment by Zwillinge** [comment]
Madoka is our custom engine for parsing the documentation. The *docs_add.js* and *docs_remove.js* contain configuration options for it. 

However, docs are not supposed to be used locally by users. But you can browse documentation files in the *data*  folder (except for *api*, it's an auto-generated section), edit them if needed and create pull requests for us.
