### ISSUE TITLE
ui.datatable API Docs - Missing datatable column 'hidden' property description

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/docs#32]
The 'hidden' property is mentioned [here](http://docs.webix.com/datatable__columns_configuration.html#hidingshowingcolumns) 
![screenshot_25](https://cloud.githubusercontent.com/assets/5741654/15037952/551b3904-12a8-11e6-902b-88e4afe49967.png)
but there's no any info about it provided [here](http://docs.webix.com/api__ui.datatable_columns_config.html)

**Comment by mafanya23** [comment]
The hidden attribute was added into columns' configuration description.
