### ISSUE TITLE
ui.datatable API Docs - Missing datatable column 'batch' property description

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/docs#33]
The 'batch' property is mentioned [here](http://docs.webix.com/datatable__columns_configuration.html#settinghiddenvisiblecolumnsingroups)
![screenshot_27](https://cloud.githubusercontent.com/assets/5741654/15066538/8eaf7d2c-1372-11e6-9a88-03ef04ab7fdc.png)
but there's no any info about it provided [here](http://docs.webix.com/api__ui.datatable_columns_config.html)

**Comment by mafanya23** [comment]
The [attributes](http://docs.webix.com/api__ui.datatable_columns_config.html) enumerated for the columns' configuration of datatable are the basic ones. We haven't mentioned such specific attributes as the batch one to avoid possible mix-up.
