### ISSUE TITLE
DataTable columns Drag'n'Drop Events

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/docs#34]
DataTable columns Drag'n'Drop Events [doc](http://docs.webix.com/api__ui.datatable_onaftercolumndrop_event.html) [description](http://docs.webix.com/api__ui.datatable_onbeforecolumndrag_event.html) stating that handler function takes complex context object as a parameter, actually there are string source columnId for 'drag' event and sourceId, targetId for the 'drop' one with no any context object.

**Comment by mafanya23** [comment]
Hello! You are right, we will update the description of these events. Thanks for reporting!
