### ISSUE TITLE
onChange event on uploader wont work

### ISSUE THREAD

**Issue by muhammadfarizarya** [webix-hub/docs#35]
I have build UI using webix, but I have trouble on using event onChange on component uploder, I have tried example code on webix docs but it still not work, any advice? thank you

**Comment by Sinode** [comment]
Basically, the `onChange` event occurs immediately after the `onFileUpload`. Can you please clarify, which sample are you using? For example, [here](http://docs.webix.com/samples/21_upload/01_init_list.html) and [here](http://docs.webix.com/samples/21_upload/03_manual_send.html) all works fine.

**Comment by muhammadfarizarya** [comment]
I've tried ini this [docs](http://docs.webix.com/api__link__ui.uploader_onchange_event.html), so `onChange` no triggered on files add/remove?

**Comment by Sinode** [comment]
No. Sorry fo the inaccuracy, we will correct the Docs. As for the needed features, there're two ways:

1. To define the `onAfterFileAdd` event and attach the `onAfterDelete` for the uploader's DataCollection as follows:
`$$("upl1").files.attachEvent("onAfterDelete", function(){ })`
2. To attach the `onStoreUpdated` to the ui.list DataStore:
`"data->onStoreUpdated":function(){   }`

Please check the following snippet to see how it works:
http://webix.com/snippet/1cc6a5e7

**Comment by muhammadfarizarya** [comment]
Oh so there is onAfterDelete event, on [this](http://docs.webix.com/api__refs__ui.uploader_events.html) documentation there is no description about onAfterDelete event
oh one more thing, on webix snippet I open using firefox just show script like this
![screenshot from 2016-05-31 08 45 41](https://cloud.githubusercontent.com/assets/3858791/15660877/1d22eaba-270c-11e6-8615-ae3a2f89d5e1.png)
thank you

**Comment by Sinode** [comment]
The mentioned event is related to the DataCollection (available as `uploader.files`). 
More information you can find [here](http://docs.webix.com/desktop__file_upload.html#manipulationswithfiles).
Also, here's the general [Data Collection API](http://docs.webix.com/desktop__file_upload.html#manipulationswithfiles).
