### ISSUE TITLE
a question about the event 'onEditorChange' around ui.datatable.

### ISSUE THREAD

**Issue by enforceway** [webix-hub/docs#40]
dataTable.attachEvent("onEditorChange", function(id, value) {
    var item = dataTable.getItem(id.row);
    console.log(item);
});
is there any possibility that the value of 'item' here is undefined?
in what situations it might this occur?

**Comment by Maria-Staskova** [comment]
I don't have ideas about the situation that might cause such an issue ? Could you please provide a [snippet](http://webix.com/snippet/) for it ?

**Comment by enforceway** [comment]
sorry for missing you up. I used onEditorChange event in an incorrect way.
